server:
  port: 30001
spring:
  application:
    name: manageservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/looport?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jhdz
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    initalSize: 5
    maxActive: 10
    maxWait: 60000
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: localhost  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    timeout: 5000  # 连接超时时间（毫秒）
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 50  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接

mybatis:

  type-aliases-package: com.yollweb.looport.entity
  mapperLocations: classpath:/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: manageservice
    prefer-ip-address: true     #访问路径可以显示IP地址
