server:
  port: 7001
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false   #不注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/